Update page about
skljor/Diploma-project pull request #11
Opened 2023-10-03 17:16 UTC by skljor

Diko nasral v page about

2023-10-03 18:13 UTC, vesnanervah requested changes

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +    <div>
Почему див безымянный? Как не зная контекста понять, что из себя представляет сущность?

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +            <span>
Ненужный span, который не делает ничего

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +            <span>
Ещё ненужный спен

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +            <span>
Опять ненужный спен

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +            <span class="bold-font job-title-center">
У тебя карточки имеют одну и ту же структуру. Почему не занеймить их нормально, чтобы можно было реализовать реюз? Что значит bold-font job-title-center и далее безымянные дивы? По названию класса ты должен понимать содержимое, даже не зная содержимого.

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +            <span>
Снова ненужные спены

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +    <p class="red-line">
Red-line - это название независимой сущности в лучшем случае. Нарисованой разделительной линии, например. Если ты работаешь с текстом, то такой нейминг недопустим.

2023-10-03 18:13 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +<div>
Где нейминг? Дальше все дивы идут с одинаковой структурой, имеет смысл дать им одинаковый нейм для обозначения.

2023-10-03 18:30 UTC, vesnanervah requested changes

2023-10-03 18:30 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +    <ul class="non-marker-list">
Нормальный нейминг? типа about__contacts или about__contacts-list?

2023-10-03 18:30 UTC, vesnanervah commented on src/app/page-about/page-about.component.html
> +<div>
about__ordeals?

2023-10-03 18:30 UTC, vesnanervah commented on src/app/page-about/page-about.component.scss
> +}
Неужели весь текст одним цветом?

2023-10-03 18:37 UTC, skljor commented on src/app/page-about/page-about.component.scss
> +}
> Неужели весь текст одним цветом?

цветом?

2023-10-05 11:37 UTC, vesnanervah approved these changes

2023-10-05 11:37 UTC, merged